export enum Actions {
    ADD_CARD= 'ADD_CARD',
    ADD_TASK= 'ADD_TASK',
    RENAME_TASK= 'RENAME_TASK',
    DRAG_DROP_CARD= 'DRAG_DROP_CARD',
    ADD_CHECKLIST_DETAILS= 'ADD_CHECKLIST_DETAILS',
    ADD_DESCRIPTION= 'ADD_DESCRIPTION',
    UPDATE_LABELS= 'UPDATE_LABELS',
    UPDATE_CHECKLIST= 'UPDATE_CHECKLIST',
    SELECT_CARD= 'SELECT_CARD',
    RESET= 'RESET',
}